// <auto-generated />
using System;
using EPlast.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EPlast.DataAccess.Migrations
{
    [DbContext(typeof(EPlastDBContext))]
    [Migration("20200415160525_Set-Nullable-dateOfBirthday")]
    partial class SetNullabledateOfBirthday
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EPlast.DataAccess.Entities.AdminType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminTypeName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("AdminTypes");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.AnnualReport", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<int>("ContributionFunds");

                    b.Property<DateTime>("Date");

                    b.Property<string>("ImprovementNeeds");

                    b.Property<string>("ListProperty");

                    b.Property<int>("NumberOfAdministrators");

                    b.Property<int>("NumberOfBeneficiaries");

                    b.Property<int>("NumberOfClubs");

                    b.Property<int>("NumberOfHonoraryMembers");

                    b.Property<int>("NumberOfIndependentGroups");

                    b.Property<int>("NumberOfIndependentRiy");

                    b.Property<int>("NumberOfPlastpryiatMembers");

                    b.Property<int>("NumberOfSeatsInCity");

                    b.Property<int>("NumberOfSeatsPtashat");

                    b.Property<int>("NumberOfTeacherAdministrators");

                    b.Property<int>("NumberOfTeachers");

                    b.Property<int>("PlastSalary");

                    b.Property<int>("PublicFunds");

                    b.Property<int>("SponsorshipFunds");

                    b.Property<int>("Status");

                    b.Property<string>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("AnnualReports");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Approver", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("UserId");

                    b.ToTable("Approvers");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityURL")
                        .HasMaxLength(256);

                    b.Property<string>("Description")
                        .HasMaxLength(1024);

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Logo")
                        .HasMaxLength(2147483647);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("OfficeNumber")
                        .HasMaxLength(10);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(16);

                    b.Property<string>("PostIndex")
                        .HasMaxLength(7);

                    b.Property<int?>("RegionID");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("ID");

                    b.HasIndex("RegionID");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.CityAdministration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminTypeId");

                    b.Property<int>("CityId");

                    b.Property<DateTime?>("EndDate");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("AdminTypeId");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("CityAdministrations");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.CityDocumentType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("CityDocumentTypes");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.CityDocuments", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityDocumentTypeID");

                    b.Property<int?>("CityID");

                    b.Property<string>("DocumentURL")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<DateTime?>("SubmitDate");

                    b.HasKey("ID");

                    b.HasIndex("CityDocumentTypeID");

                    b.HasIndex("CityID");

                    b.ToTable("CityDocuments");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.CityLegalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<DateTime?>("DateFinish");

                    b.Property<DateTime>("DateStart");

                    b.Property<int>("LegalStatusType");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("CityLegalStatuses");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.CityManagement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnualReportId");

                    b.Property<int?>("CityAdminOldId");

                    b.Property<int>("CityLegalStatusNew");

                    b.Property<int?>("CityLegalStatusOldId");

                    b.Property<string>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("AnnualReportId")
                        .IsUnique();

                    b.HasIndex("CityAdminOldId")
                        .IsUnique()
                        .HasFilter("[CityAdminOldId] IS NOT NULL");

                    b.HasIndex("CityLegalStatusOldId")
                        .IsUnique()
                        .HasFilter("[CityLegalStatusOldId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("CityManagements");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.CityMembers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<DateTime?>("EndDate");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("CityMembers");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Club", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ClubURL");

                    b.Property<string>("Description")
                        .HasMaxLength(1024);

                    b.Property<string>("Logo");

                    b.HasKey("ID");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.ClubAdministration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdminTypeID");

                    b.Property<int?>("ClubID");

                    b.Property<int>("ClubMembersID");

                    b.Property<DateTime?>("EndDate");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("ID");

                    b.HasIndex("AdminTypeID");

                    b.HasIndex("ClubID");

                    b.HasIndex("ClubMembersID");

                    b.ToTable("ClubAdministrations");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.ClubMembers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClubID");

                    b.Property<bool>("IsApproved");

                    b.Property<string>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("ClubID");

                    b.HasIndex("UserId");

                    b.ToTable("ClubMembers");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.ConfirmedUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApproverID");

                    b.Property<DateTime>("ConfirmDate");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("ApproverID")
                        .IsUnique()
                        .HasFilter("[ApproverID] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("ConfirmedUsers");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Decesion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("DecesionStatusType");

                    b.Property<int>("DecesionTargetID");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<bool>("HaveFile");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("OrganizationID");

                    b.HasKey("ID");

                    b.HasIndex("DecesionTargetID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Decesions");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.DecesionTarget", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("DecesionTargets");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Degree", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("Degrees");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.DocumentTemplate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DocumentFIleName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("DocumentTemplates");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Education", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PlaceOfStudy")
                        .HasMaxLength(50);

                    b.Property<string>("Speciality")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("EventCategoryID");

                    b.Property<DateTime>("EventDateEnd");

                    b.Property<DateTime>("EventDateStart");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("EventStatusID");

                    b.Property<int>("EventTypeID");

                    b.Property<string>("Eventlocation")
                        .IsRequired();

                    b.Property<string>("ForWhom")
                        .IsRequired();

                    b.Property<string>("FormOfHolding")
                        .IsRequired();

                    b.Property<int>("NumberOfPartisipants");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("ID");

                    b.HasIndex("EventCategoryID");

                    b.HasIndex("EventStatusID");

                    b.HasIndex("EventTypeID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.EventAdmin", b =>
                {
                    b.Property<int>("EventID");

                    b.Property<string>("UserID");

                    b.HasKey("EventID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("EventAdmin");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.EventAdministration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdministrationType");

                    b.Property<int>("EventID");

                    b.Property<string>("UserID")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("EventID");

                    b.HasIndex("UserID");

                    b.ToTable("EventAdministration");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.EventCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EventCategoryName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("EventCategories");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.EventGallary", b =>
                {
                    b.Property<int>("EventID");

                    b.Property<int>("GallaryID");

                    b.HasKey("EventID", "GallaryID");

                    b.HasIndex("GallaryID");

                    b.ToTable("EventGallarys");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.EventStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EventStatusName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("EventStatuses");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.EventType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EventTypeName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Gallary", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GalaryFileName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Gallarys");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Gender", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(10);

                    b.HasKey("ID");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.MembersStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnnualReportId");

                    b.Property<int>("NumberOfNovatstva");

                    b.Property<int>("NumberOfPtashata");

                    b.Property<int>("NumberOfSeigneurMembers");

                    b.Property<int>("NumberOfSeigneurSupporters");

                    b.Property<int>("NumberOfSeniorPlastynMembers");

                    b.Property<int>("NumberOfSeniorPlastynSupporters");

                    b.Property<int>("NumberOfUnatstvaMembers");

                    b.Property<int>("NumberOfUnatstvaNoname");

                    b.Property<int>("NumberOfUnatstvaProspectors");

                    b.Property<int>("NumberOfUnatstvaSkobVirlyts");

                    b.Property<int>("NumberOfUnatstvaSupporters");

                    b.HasKey("Id");

                    b.HasIndex("AnnualReportId")
                        .IsUnique();

                    b.ToTable("MembersStatistics");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Nationality", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(25);

                    b.HasKey("ID");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Organization", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OrganizationName");

                    b.HasKey("ID");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Participant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventId");

                    b.Property<int>("ParticipantStatusId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("EventId");

                    b.HasIndex("ParticipantStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.ParticipantStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ParticipantStatusName")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("ParticipantStatuses");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Region", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(1024);

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.RegionAdministration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminTypeID");

                    b.Property<DateTime?>("EndDate");

                    b.Property<int?>("RegionID");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("AdminTypeID");

                    b.HasIndex("RegionID");

                    b.HasIndex("UserId");

                    b.ToTable("RegionAdministrations");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Religion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(25);

                    b.HasKey("ID");

                    b.ToTable("Religions");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.UnconfirmedCityMember", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityID");

                    b.Property<string>("UserId");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.HasIndex("UserId");

                    b.ToTable("UnconfirmedCityMember");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.UserPlastDegree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateFinish");

                    b.Property<DateTime>("DateStart");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.Property<int>("UserPlastDegreeType");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPlastDegrees");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.UserProfile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("DateTime");

                    b.Property<int?>("DegreeId");

                    b.Property<int?>("EducationId");

                    b.Property<int?>("GenderID");

                    b.Property<int?>("NationalityId");

                    b.Property<int?>("ReligionId");

                    b.Property<string>("UserID");

                    b.Property<int?>("WorkId");

                    b.HasKey("ID");

                    b.HasIndex("DegreeId");

                    b.HasIndex("EducationId");

                    b.HasIndex("GenderID");

                    b.HasIndex("NationalityId");

                    b.HasIndex("ReligionId");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.HasIndex("WorkId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Work", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PlaceOfwork")
                        .HasMaxLength(30);

                    b.Property<string>("Position")
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FatherName")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ImagePath");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("RegistredOn");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.AnnualReport", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.City", "City")
                        .WithMany("AnnualReports")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.User", "User")
                        .WithMany("AnnualReports")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Approver", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.User", "User")
                        .WithMany("Approvers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.City", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionID");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.CityAdministration", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.AdminType", "AdminType")
                        .WithMany("CityAdministration")
                        .HasForeignKey("AdminTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.City", "City")
                        .WithMany("CityAdministration")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.User", "User")
                        .WithMany("CityAdministrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.CityDocuments", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.CityDocumentType", "CityDocumentType")
                        .WithMany("CityDocuments")
                        .HasForeignKey("CityDocumentTypeID");

                    b.HasOne("EPlast.DataAccess.Entities.City", "City")
                        .WithMany("CityDocuments")
                        .HasForeignKey("CityID");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.CityLegalStatus", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.City", "City")
                        .WithMany("CityLegalStatuses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.CityManagement", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.AnnualReport", "AnnualReport")
                        .WithOne("CityManagement")
                        .HasForeignKey("EPlast.DataAccess.Entities.CityManagement", "AnnualReportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.CityAdministration", "CityAdminOld")
                        .WithOne("CityManagement")
                        .HasForeignKey("EPlast.DataAccess.Entities.CityManagement", "CityAdminOldId");

                    b.HasOne("EPlast.DataAccess.Entities.CityLegalStatus", "CityLegalStatusOld")
                        .WithOne("CityManagement")
                        .HasForeignKey("EPlast.DataAccess.Entities.CityManagement", "CityLegalStatusOldId");

                    b.HasOne("EPlast.DataAccess.Entities.User", "CityAdminNew")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.CityMembers", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.City", "City")
                        .WithMany("CityMembers")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.User", "User")
                        .WithMany("CityMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.ClubAdministration", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.AdminType", "AdminType")
                        .WithMany("ClubAdministration")
                        .HasForeignKey("AdminTypeID");

                    b.HasOne("EPlast.DataAccess.Entities.Club", "Club")
                        .WithMany("ClubAdministration")
                        .HasForeignKey("ClubID");

                    b.HasOne("EPlast.DataAccess.Entities.ClubMembers", "ClubMembers")
                        .WithMany("ClubAdministration")
                        .HasForeignKey("ClubMembersID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.ClubMembers", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.Club", "Club")
                        .WithMany("ClubMembers")
                        .HasForeignKey("ClubID");

                    b.HasOne("EPlast.DataAccess.Entities.User", "User")
                        .WithMany("ClubMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.ConfirmedUser", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.Approver", "Approver")
                        .WithOne("ConfirmedUser")
                        .HasForeignKey("EPlast.DataAccess.Entities.ConfirmedUser", "ApproverID");

                    b.HasOne("EPlast.DataAccess.Entities.User", "User")
                        .WithMany("ConfirmedUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Decesion", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.DecesionTarget", "DecesionTarget")
                        .WithMany()
                        .HasForeignKey("DecesionTargetID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Event", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.EventCategory", "EventCategory")
                        .WithMany("Events")
                        .HasForeignKey("EventCategoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.EventStatus", "EventStatus")
                        .WithMany("Events")
                        .HasForeignKey("EventStatusID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.EventAdmin", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.Event", "Event")
                        .WithMany("EventAdmins")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.EventAdministration", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.Event", "Event")
                        .WithMany("EventAdministrations")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.EventGallary", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.Event", "Event")
                        .WithMany("EventGallarys")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.Gallary", "Gallary")
                        .WithMany("Events")
                        .HasForeignKey("GallaryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.MembersStatistic", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.AnnualReport", "AnnualReport")
                        .WithOne("MembersStatistic")
                        .HasForeignKey("EPlast.DataAccess.Entities.MembersStatistic", "AnnualReportId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.Participant", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.ParticipantStatus", "ParticipantStatus")
                        .WithMany("Participants")
                        .HasForeignKey("ParticipantStatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.User", "User")
                        .WithMany("Participants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.RegionAdministration", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.AdminType", "AdminType")
                        .WithMany("RegionAdministration")
                        .HasForeignKey("AdminTypeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.Region", "Region")
                        .WithMany("RegionAdministration")
                        .HasForeignKey("RegionID");

                    b.HasOne("EPlast.DataAccess.Entities.User", "User")
                        .WithMany("RegionAdministrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.UnconfirmedCityMember", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.City", "City")
                        .WithMany("UnconfirmedCityMember")
                        .HasForeignKey("CityID");

                    b.HasOne("EPlast.DataAccess.Entities.User", "User")
                        .WithMany("UnconfirmedCityMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.UserPlastDegree", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.User", "User")
                        .WithMany("UserPlastDegrees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EPlast.DataAccess.Entities.UserProfile", b =>
                {
                    b.HasOne("EPlast.DataAccess.Entities.Degree", "Degree")
                        .WithMany("UserProfiles")
                        .HasForeignKey("DegreeId");

                    b.HasOne("EPlast.DataAccess.Entities.Education", "Education")
                        .WithMany("UsersProfiles")
                        .HasForeignKey("EducationId");

                    b.HasOne("EPlast.DataAccess.Entities.Gender", "Gender")
                        .WithMany("UserProfiles")
                        .HasForeignKey("GenderID");

                    b.HasOne("EPlast.DataAccess.Entities.Nationality", "Nationality")
                        .WithMany("UserProfiles")
                        .HasForeignKey("NationalityId");

                    b.HasOne("EPlast.DataAccess.Entities.Religion", "Religion")
                        .WithMany("UserProfiles")
                        .HasForeignKey("ReligionId");

                    b.HasOne("EPlast.DataAccess.Entities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("EPlast.DataAccess.Entities.UserProfile", "UserID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EPlast.DataAccess.Entities.Work", "Work")
                        .WithMany("UserProfiles")
                        .HasForeignKey("WorkId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
