apiVersion : apps/v1
kind: Deployment
metadata:
  name: eplastbackend
  labels:
    app: eplastbackend  
spec:
  selector:
    matchLabels:
      app: eplastbackend
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: eplastbackend 
    spec:
      containers:
        - name: eplastbackend 
          image: ___containerRegistry___/eplastbackend
          resources:
            limits:
              cpu: "500m"
              memory: "1000Mi"
            requests:
              cpu: "250m"
              memory: "500Mi"   
          ports:
          - containerPort: 5000
          env:
          - name: ConnectionStrings__EPlastDBConnection
            value: ___ConnectionStrings__EPlastDBConnection___
          - name: StorageConnectionString
            value: ___StorageConnectionString___
          - name: EmailServiceSettings__SMTPServerLogin
            value: ___EmailServiceSettings__SMTPServerLogin___
          - name: EmailServiceSettings__SMTPServerPassword
            value: ___EmailServiceSettings__SMTPServerPassword___
          - name: Admin__Email
            value: ___Admin__Email___
          - name: Admin__Password
            value: ___Admin__Password___
          - name: GoogleAuthentication__GoogleClientId
            value: ___GoogleAuthentication__GoogleClientId___
          - name: GoogleAuthentication__GoogleClientSecret
            value: ___GoogleAuthentication__GoogleClientSecret___
          - name: FacebookAuthentication__FacebookAppId
            value: ___FacebookAuthentication__FacebookAppId___
          - name: FacebookAuthentication__FacebookAppSecret
            value: ___FacebookAuthentication__FacebookAppSecret___
            
# ---
# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: eplastbackend-autoscaler
#   namespace: eplast
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: eplastbackend
#   minReplicas: 1
#   maxReplicas: 3
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       targetAverageUtilization: 70
#   - type: Resource
#     resource:
#       name: memory
#       targetAverageUtilization: 80            

---
apiVersion: v1
kind: Service
metadata:
    name: eplastbackend
spec:
    type: ClusterIP
    ports:
    - port: 5000 
    selector:
        app: eplastbackend

# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: eplastbackend-autoscaler
#   namespace: eplast
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: eplastbackend
#   minReplicas: 1
#   maxReplicas: 3
#   targetCPUUtilizationPercentage: 60

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: eplastbackend-autoscaler
  namespace: eplast
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eplastbackend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: AverageValue
  #       averageValue: 75