export const AUTH_LOADING = 'AUTH_LOADING';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
